version: '3.8'

services:
  customer-db:
    image: mariadb:latest
    container_name: customer-db
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: customer_db
    ports:
      - "3306:3306"

  customer-service:
    build: .
    container_name: customer-service1
    ports:
      - "8082:8082"
    depends_on:
      - customer-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://customer-db:3306/customer_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

